COMPILER = gcc
TARGET = keycopy
SRC_DIR = src
INCLUDE_DIR = include
CFLAGS = -I$(INCLUDE_DIR) -Wall
LDFLAGS = 
BUILD_DIR = build

$(TARGET): $(BUILD_DIR)/main.o
	 $(COMPILER) $^ -o $@ $(LDFLAGS)

$(BUILD_DIR)/main.o: $(SRC_DIR)/main.c $(INCLUDE_DIR)/main.h
	$(COMPILER) $(CFLAGS) $< -o $@ 

.PHONY: clean

clean:
	rm -f $(BUILD_DIR)/*.o
